version: '3'

services:
  php-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
      - ./tmp:/tmp
      - ./conf/nginx.conf:/etc/nginx/sites-available/default
      - ./conf/php.ini:/etc/php/7.2/fpm/php.ini
    ports:
      - 80:80
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    networks:
      - docker-env_net-service

networks:
  docker-env_net-service:
    external: true
  